spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/course-work-db
  liquibase:
    change-log: classpath:migrations/changelog.yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: ru.student.backend.db.handler
